### ISSUE TITLE
Is diagon support Windows?

### ISSUE THREAD

**Issue by hungpham3112** [ArthurSonzogni/Diagon#28]
I read README.md but didn't find anything about installation in windows.

**Comment by ArthurSonzogni** [comment]
I don't think there are strong blockers for windows build. However, I didn't manage myself:
https://github.com/ArthurSonzogni/Diagon/blob/master/.github/workflows/continuous-integration.yaml#L48

The only difficulty is running ANTLR.

**Comment by HungPham3112** [comment]
Can you show me the way to install Diagon in Window?. I'm new with this

**Comment by ArthurSonzogni** [comment]
I would try to open the CMakeList.txt using cmake (or maybe visual studio)
This should work, but you might see errors.

Also, I believe you might see errors with regards to boost. I think I have to find something to install it.

**Comment by ArthurSonzogni** [comment]
Windows binaries have been released:
https://github.com/ArthurSonzogni/Diagon/releases/tag/v1.0.139

**Comment by asmwarrior** [comment]
Hi, I'm here to report an issue about running the Windows executable.

When I run the file "diagon-1.0.139-win64\bin>diagon.exe" I extract from the "diagon-1.0.139-win64.zip", I got an error message that said:

~~~~
---------------------------
diagon.exe - 系统错误
---------------------------
无法启动此程序，因为计算机中丢失 MSVCP140D.dll。尝试重新安装该程序以解决此问题。 
---------------------------
确定   
---------------------------
~~~~

To translate to English word, it said the `MSVCP140D.dll` file is missing. The problem here is the file with `D` means it is the debug version of the library. I think for a release, you should supply the exe file which depends on a release version of the dll.

See reference here: [MSVCP140d.dll - Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/806905/msvcp140d-dll)

Thanks.

**Comment by ArthurSonzogni** [comment]
Hello @asmwarrior,
Thanks for reporting this.
Do you know how to do it?
The release version are compiled in release mode:
https://github.com/ArthurSonzogni/Diagon/blob/413132bc56948514d425d0d865b4fb83408e74b2/.github/workflows/continuous-integration.yaml#L227

Not sure if there are something more I can do.
